const mongoose = require("mongoose");
const resourceschema = new mongoose.Schema(
    {
        title:{
            type:String,
            required:true,
            trim:true
        },
        description:{
            type:String,
            trim:true,
            default:""
        },
        category:{
            type:String,
            enum:[
                "DSA",
                "DBMS",
                "OS",
                "CN",
                "REACT",
                "WEB_DEVELOPEMENT",
                "NOTES",
                "OTHER"
            ],
            required:true,
        },
        fileUrl:{
            type:String,
            required:true,
        },
        fileName:{
            type:String,
            required:true,

        },
        fileType:{
            type:String,
            required:true,
        },
        fileSize:{
            type:Number,
            required:true,
        },
        uploadedBy:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"User",
            required:true,
        },
        downloadCount:{
            type:Number,
            default:0,
        },
        status:{
            type:String,
            enum:["PENDING","APPROVED","REJECTED"],
            default:"PENDING"
        },
    },
    {
        timestamps:true
    }
);

const Resource=mongoose.model("Resource",resourceschema);
module.exports=Resource;