const mongoose = require("mongoose");
const taskSchema= new mongoose.Schema(
    {
        title:{
            type:String,
            required:true,
            trim:true,
        },
        description:{
            type:String,
            default:"",
            trim:true,
        },
        club:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"Club",
            required:true,
        },
        assignedTo:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"User",
            required:true,
        },
        assignedBy:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"User",
            required:true,
        },
        dueDate:{
            type:Date,
            required:true,
        },
    },
    {
        timestamps:true,
    }
);
const Task=mongoose.model("Task",taskSchema);
module.exports=Task;